### ISSUE TITLE
Having trouble determining module name

### ISSUE THREAD

**Issue by JulianBirch** [chrisdone/ghci-ng#9]
From my emacs log (new setup, based on yours)

```
-> :type-at /home/julian/semele/src/Application.hs 12 14 12 17 get
<- Couldn't guess that module name. Does it exist?
```

Could you explain a bit about how it guesses?

Thanks,

**Comment by chrisdone** [comment]
Did you enable `:set +c`? Also try `:set -fobject-code`, if you have `.o` files next to your `.hs` files, this flag will make sure GHCi updates them. You should see "Collecting type info ..." in the log if collection is working.

**Comment by JulianBirch** [comment]
Thankyou! I thought I had but the file was being ignored for chmod reasons. I've got it working now.

Now to get back to reading the intro... :)

**Comment by mmaz** [comment]
I'm having a similar problem. In my haskell-process-log, I see 

```
Ok, modules loaded: Foo, Main, ...[omitted other module names].
   Collecting type info for 8 module(s) ... 
```

I can inspect types with `:type-at` in my `Main` module, including imports from the `Foo` module. But when I open `Foo.hs` in emacs, I see the _"Couldn't guess that module name. Does it exist?"_ message. This happens whether or not I run `haskell-process-load-or-reload` after opening `Foo.hs`. Could this be due to my project not following a standard cabal project layout or module-naming convention? (e.g., multiple executables in my `.cabal`, and module `Main` is defined in `bar.hs`)

**Comment by chrisdone** [comment]
Does it say `Collecting type info` when you load the module in Emacs? Check under [*haskell-process-log*](https://github.com/haskell/haskell-mode/wiki/Haskell-Interactive-Mode-Setup#troubleshooting).

**Comment by mmaz** [comment]
@chrisdone thanks for the reply. I have good news: I deleted my `dist/` directory and after it was recreated, now I can perform type inspection again with ghci-ng. I'm not sure why I had to delete the build directory though. If it helps, I will include a little more information here, but my apologies that I can't link to the actual non-public code. I have a directory layout like this:

```
Foo.hs
bar.hs
baz.hs
myproject.cabal
```

where `myproject.cabal` defines a couple of executables from `--main-is bar.hs` and `--main-is baz.hs`, and in my case `bar.hs` is roughly:

```
import qualified Foo as F

barify :: ..
barify = ...

main = ... barify $  F.fooify ...
```

I see `Collecting type info` in `haskell-process-log` when I bring the repl from `bar.hs` by `haskell-process-load-or-reload`. Inside `bar.hs` I can then inspect types (`haskell-mode-show-type-at`) on both `barify` and `F.fooify` successfully.

But then if I opened one of the modules that `bar.hs` imports (`Foo.hs`) with `C-x C-f Foo.hs` I could no longer perform type inspection. I also noted that, from the terminal if I directly open `Foo.hs`:

```
$ emacs Foo.hs &
```

I saw this in `haskell-process-log`:

```
   Ok, modules loaded: Main, Foo, etc, etc....
   Collecting type info for 8 module
<- (s) ... 

-> :load ".../Foo.hs"
<- 
   
<- [1 of 1] Compiling Foo        ( /..../Foo.hs, interpreted )
   
<- Ok, modules loaded: Foo.
```

but did not get a second `Collecting type info` message for Foo after `modules loaded: Foo`. After I deleted my `dist/` folder, I am now seeing additional `Collecting type info` messages again after running `haskell-process-load-or-reload` from other modules I open. 

I will reply if I can reproduce the issue again, but for now everything seems fine for me. In any case, if others who are new to ghci-ng run into this issue with existing projects, maybe they too should first try to delete their build directory (although I'm not sure why that helped me out, since I had rebuilt the project and ran `cabal test` after my last comment a couple of times, so I assume my `dist/` directory wasn't out of sync with the project and I haven't changed any platform or dependency versions recently.)

**Comment by chrisdone** [comment]
I think this is an instance of #1 which I don't currently have a solution for, but I think I can make `ghci-ng` detect whether the `-fobject-code` or `-fbyte-code` (GHCi's default) is enabled or not and then do caching appropriately.

**Comment by chrisdone** [comment]
Longer explanation: If a process like `cabal build` or `cabal repl` loaded your modules, it will have done so in a way that creates `.o` files, presumably in your `dist`, which makes `ghci-ng` thing that your module hasn't changed because the `.o` file has not been updated: https://github.com/chrisdone/ghci-ng/blob/master/ghc/GhciInfo.hs#L55..L66

I can't remember why I'm using the `.o` file rather than just the `.hs` file, however… Ah! That's why: If module Car imports module Wheel and then you update `Wheel.hs`, that will cause both `Wheel.o` and `Car.o` to be modified because both modules have to be recompiled now.

**Comment by mmaz** [comment]
Ah, thanks again! That makes sense. Also, my _sincere_ thanks for ghci-ng! It works like an absolute charm, and I'm very happy. I decided to try switching since ghc-mod is not currently working for me (I believe it's due to [this issue regarding cabal 1.22 on 7.8](https://github.com/kazu-yamamoto/ghc-mod/issues/417)) and I felt helpless without type inspection :)

**Comment by chrisdone** [comment]
Hehe, glad you like. :)
